import:
 - control/action
 - control/keyboard/qwerty
 - control/workdir
 - display/client
 - display/desktop/xsetroot
 - display/tags
 - display/status/network/ifstat
 - display/status/storage/df
 - display/status/system/loadavg
 - display/status/volume/amixer
 - display/status/trayer
 - display/status/power/acpi
 - display/status/time
 - display/notice
 - control/named-tags

prefer:
  terminal: urxvtc
  browser:  firefox
  editor:   gvim
  filer:    thunar

display:
  bar:    bottom
  font:   xft:Monospace:pixelsize=10:antialias=1:hinting=1:hintstyle=hintfull:rgba=none
  border: 2
  notice: 5

  color:
    desktop:  "#eeeeef"
    focus:    "#2A2A4A #CECEDE #5A5A8A"
    normal:   "#3A3A6A #EEEEEF #DADAEA"
    error:    "#EF0020 #FBD3E4 #FF0020"
    notice:   "#514721 #FFF6BF #FFD324"
    success:  "#264409 #E6EFE2 #B6D870"

  column:
    mode: default
    rule: |
      /art/ -> 17+83+17
      /.*/ -> 62+38
  status:
    loadavg:
      refresh: 5
      high: 2
      ciritcal: 5
    acpi:
      battery: BAT0
    ifstat:
      device: br0
    time:
      label: Time.now.strftime("%a %d.%m. %H:%M")
      mouse_action:
        right_click: lock_screen

control:
  action:
    show_calendar: launch 'wxremind'
    lock_screen:  launch 'slock'

  mouse:
  keyboard:
    grabmod: Mod4

    mod:     Mod4
    move:    Mod4-Shift
    swap:    Mod4-r
    view:    Mod4-Shift-v
    group:   Mod4-g
    layout:  Mod4-z
    arrange: Mod4-Shift-z

  keyboard_action:
    ${mod}-q: kill_current_client

  event:
    ClientClick: |
      case Mouse[argv[1]]
      when 'wheel_up'    then action 'focus_above_client'
      when 'wheel_down'  then action 'focus_below_client'
      end

    LeftBarMouseDown: |
      case Mouse[argv[0]]
      when 'wheel_up'    then action 'focus_previous_view'
      when 'wheel_down'  then action 'focus_next_view'
      end


script:
  - before:
  - after: |
      launch 'urxvtd'
