import:
 - control/action
 - control/keyboard/qwerty
 - control/workdir
 - display/client
 - display/desktop/xsetroot
 - display/tags
 - display/status/network/ifstat
 - display/status/storage/df
 - display/status/system/loadavg
 - display/status/volume/amixer
 - display/status/trayer
 - display/status/power/acpi
 - display/status/time
 - display/notice
 - control/named-tags
 - display/color/cadmium

prefer:
  terminal: urxvtc
  browser:  firefox
  editor:   gvim
  filer:    thunar

display:
  bar:    bottom
  font:   xft:Monospace:pixelsize=10:antialias=1:hinting=1:hintstyle=hintfull:rgba=none
  border: 2
  notice: 5

  column:
    mode: default
    rule: |
      /art/ -> 17+83+17
      /.*/ -> 62+38
  status:
    loadavg:
      refresh: 5
      high: 2
      ciritcal: 5
    acpi:
      battery: BAT0
    ifstat:
      device: br0
    time:
      label: Time.now.strftime("%a %d.%m. %H:%M")
      mouse_action:
        right_click: lock_screen

control:
  action:
    show_calendar: launch 'wxremind'
    lock_screen:  launch 'slock'
    remove_grouping_from_current_view: grouping.each { |c| c.untag curr_tag }

  keyboard:
    grabmod: Mod4

    mod:     Mod4
    move:    Mod4-Shift
    swap:    Mod4-r
    group:   Mod4-g
    layout:  Mod4-z
    arrange: Mod4-Shift-z
    view:    Mod4-o

  keyboard_action:
    ${mod}-q:       kill_current_client
    ${mod}-Shift-q: remove_grouping_from_current_view
    ${mod}-y:       toggle_current_client_from_grouping

    ${mod}-i:       focus_client_from_menu
    ${mod}-Shift-i: invite_client_from_menu

    ${mod}-Shift-c: change_tagdir

    ${mod}-Tab:     focus_most_recently_focused_view
    ${mod}-o,space: focus_most_recently_focused_view
    ${mod}-e:

  event:
    ClientClick: |
      case Mouse[argv[1]]
      when 'wheel_up'    then action 'focus_above_client'
      when 'wheel_down'  then action 'focus_below_client'
      end

    LeftBarMouseDown: |
      case Mouse[argv[0]]
      when 'wheel_up'    then action 'focus_previous_view'
      when 'wheel_down'  then action 'focus_next_view'
      end


script:
  - after: |
      launch 'urxvtd'
